name: Otomatik Playlist Guncelleme

on:
  schedule:
    - cron: '*/30 * * * *' # 30 dakikada bir çalışacak şekilde hızlandırdık
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        # cloudscraper ekledik
        run: pip install requests beautifulsoup4 cloudscraper 

      - name: Scraper'ı Çalıştır
        run: python scraper.py

      - name: Değişiklikleri Kaydet
        run: |
          git config --global user.name "nookjoook56-web"
          git config --global user.email "github-actions@github.com"
          touch playlist.m3u
          git add playlist.m3u
          git diff --staged --quiet || (git commit -m "JustinTV Guncellendi: $(date)" && git push)
          
